// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABddCFM1AmTd3I9k_TW4ixolVi5CftdbU',
    appId: '1:424330738470:android:27079b4c27abd5251e5fe7',
    messagingSenderId: '424330738470',
    projectId: 'cerebrosync-b79a9',
    storageBucket: 'cerebrosync-b79a9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIWgeH4OcZ0TzbSf-kXR9-LBmzsjqSfX8',
    appId: '1:424330738470:ios:1abde49762a5348d1e5fe7',
    messagingSenderId: '424330738470',
    projectId: 'cerebrosync-b79a9',
    storageBucket: 'cerebrosync-b79a9.firebasestorage.app',
    iosBundleId: 'com.ricky.neuromotion',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKXhQJddkfelmNzxVRN0gyah5zAKccmh4',
    appId: '1:424330738470:web:e521a25a46ad34c91e5fe7',
    messagingSenderId: '424330738470',
    projectId: 'cerebrosync-b79a9',
    authDomain: 'cerebrosync-b79a9.firebaseapp.com',
    storageBucket: 'cerebrosync-b79a9.firebasestorage.app',
    measurementId: 'G-1KMBZX6DG6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIWgeH4OcZ0TzbSf-kXR9-LBmzsjqSfX8',
    appId: '1:424330738470:ios:c43d378a602a19881e5fe7',
    messagingSenderId: '424330738470',
    projectId: 'cerebrosync-b79a9',
    storageBucket: 'cerebrosync-b79a9.firebasestorage.app',
    iosBundleId: 'com.example.brainwaveApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKXhQJddkfelmNzxVRN0gyah5zAKccmh4',
    appId: '1:424330738470:web:71c42a1c9c26769e1e5fe7',
    messagingSenderId: '424330738470',
    projectId: 'cerebrosync-b79a9',
    authDomain: 'cerebrosync-b79a9.firebaseapp.com',
    storageBucket: 'cerebrosync-b79a9.firebasestorage.app',
    measurementId: 'G-B4ZWV90TW4',
  );
}
